### ISSUE TITLE
Not finding AppleTV

### ISSUE THREAD

**Issue by djacobs23** [stickpin/node-appletv-x#2]
I am using version 1.0.16 and it is not finding any applets (I have 8) it says latest version is 1.0.17 but it will not install that version. is the latest version published correctly?

**Comment by stickpin** [comment]
Yes, it's published correctly: https://www.npmjs.com/package/node-appletv-x

**Comment by djacobs23** [comment]
thanks 

still installing 1.0.16

Thanks,

Doug Jacobs
513-739-9471
